[package]
name = "shared"
version = "0.1.0"

[parse]
parse_deps = true
include = ["shared"]

[export]
include = ["rust_core_new", "rust_core_free", "rust_core_dispatch", "rust_core_view", "rust_string_free"]
exclude = ["*"]
header = "shared.h"
language = "C"

